fix: scoreboard overflow if problems too many
hydro-dev/Hydro pull request #223
Opened 2021-09-30 10:30 UTC by BATTLEHAWK00

修复题目较多时，作业和比赛的成绩表排版

2021-09-30 11:11 UTC, undefined-moe requested changes
在题目数量较少时会产生问题

2021-09-30 11:42 UTC, BATTLEHAWK00 commented
具体是什么问题呢，我这边开了作业跟比赛是没问题的

2021-09-30 13:04 UTC, undefined-moe requested changes

2021-09-30 13:04 UTC, undefined-moe commented on packages/ui-default/pages/homework_scoreboard.page.styl
> +    width: rem(100px)
在作业中若题目数量少，排名、用户名字段会被拉长

2021-09-30 13:49 UTC, undefined-moe commented
那为什么 contest scoreboard 没有 min-width

2021-09-30 13:50 UTC, BATTLEHAWK00 commented
正在改

2021-09-30 13:53 UTC, BATTLEHAWK00 commented
现在可以了不

2021-09-30 13:57 UTC, undefined-moe commented
是否应该锁定左侧排名、用户、分数三列（？

2021-09-30 15:04 UTC, merged

2021-10-09 09:32 UTC, undefined-moe commented
@BATTLEHAWK00 悬浮状态显示异常，同时似乎将滚动条锁定更加合理

![image](https://user-images.githubusercontent.com/29992205/136652825-19ffb49d-70ba-4369-9514-f193e16cc11b.png)