core&ui: add language filter
hydro-dev/Hydro pull request #346
Opened 2022-04-24 11:17 UTC by pandadtdyy

2022-04-24 14:43 UTC, undefined-moe commented on packages/ui-default/pages/record_main.page.ts
> +  if (status) $('select[name="status"]').val(status);
我觉得是不是有必要抽离一个 getAvailableLangs 放进 utils 啊（
好几个页面都用到了）

2022-04-24 14:43 UTC, undefined-moe commented on packages/ui-default/templates/record_main.html
> +            <div class="medium-3 columns">
`nojs--hide`

2022-04-24 14:45 UTC, pandadtdyy commented on packages/ui-default/pages/record_main.page.ts
> +  if (status) $('select[name="status"]').val(status);
我觉得合理 因为codeforces啥的还有别的langs 我觉得window.LANGS在筛选的时候会出问题

2022-04-24 15:25 UTC, pandadtdyy commented on packages/ui-default/templates/record_main.html
> +            <div class="medium-3 columns">
nojs 其实不用hide 有All Languages呢XD

2022-04-25 09:22 UTC, undefined-moe requested changes

2022-04-25 09:22 UTC, undefined-moe commented on packages/ui-default/components/scratchpad/ScratchpadToolbarContainer.jsx
> +      this.props.setEditorLanguage(key || Object.keys(avaliableLangs)[0]);
```suggestion
      this.props.setEditorLanguage(key || keys[0]);
```

2022-04-25 09:22 UTC, undefined-moe commented on packages/ui-default/utils/avaliableLangs.ts
> +export default function getAvaliableLangs(langsList?) {
```suggestion
export default function getAvaliableLangs(langsList?: string[]) {
```

2022-04-25 09:22 UTC, undefined-moe commented on packages/ui-default/pages/record_main.page.ts
> +  if (status) $('select[name="status"]').val(status);
这个东西应该是后端填好的

2022-04-25 09:32 UTC, pandadtdyy commented on packages/ui-default/pages/record_main.page.ts
> +  if (status) $('select[name="status"]').val(status);
select的value用的是option里selected 不是直接赋值 之前后端template没有填 lang因为是动态的所以set
status的set是之前没处理我这边顺手补的 那不然就改成后端补10个if XD

2022-04-25 14:06 UTC, undefined-moe approved these changes

2022-04-25 14:26 UTC, merged