core&ui: add support for webauthn
hydro-dev/Hydro pull request #375
Opened 2022-06-27 06:11 UTC by CodyNotFound

2022-06-27 06:11 UTC, CodyNotFound commented
I have read the CLA Document and I hereby sign the CLA

2022-06-27 06:17 UTC, undefined-moe requested changes

2022-06-27 06:17 UTC, undefined-moe commented on package.json
> +        "webauthn-lib": "^1.0.0"
DO NOT add dependencies to project root.
move it into a specific package.

2022-06-27 06:17 UTC, undefined-moe commented on package.json
> +        "base64url": "^3.0.1",
Use NodeJS builtin base64 buffer encoder instead.

2022-06-27 06:17 UTC, undefined-moe commented on packages/ui-default/pages/home_security.page.ts
> +        delete(_: "")
remove useless argument.

2022-06-27 06:17 UTC, undefined-moe commented on packages/ui-default/templates/home_security.html
> +            {{ form.form_text({
keep the original indention.

2022-06-30 00:15 UTC, pandadtdyy requested changes

2022-06-30 00:15 UTC, pandadtdyy commented on package.json
> +        "webauthn-lib": "^1.0.0"
had better use `@simplewebauthn/server` & move to hydrooj/package.json

2022-06-30 00:15 UTC, pandadtdyy commented on packages/ui-default/templates/home_security.html
> +    {% if handler.user.mail.endsWith('.local') %}
don't use HTML format plugin format templates

2022-07-08 13:27 UTC, undefined-moe approved these changes

2022-07-08 13:27 UTC, undefined-moe commented on packages/hydrooj/locales/zh.yaml
> +'Click to show secret': 点击以显示 Secret
无必要使用引号

2022-07-08 13:27 UTC, undefined-moe commented on packages/hydrooj/src/handler/user.ts
> +        webauthnResponse = '', webauthnToken = '') {
```suggestion
    async post(
        domainId: string, uname: string, password: string, rememberme = false, 
        redirect = '', tfa = '', webauthnResponse = '', webauthnToken = '',
    ) {
```

2022-07-08 13:27 UTC, undefined-moe commented on packages/hydrooj/src/handler/user.ts
> +        if (webauthnResponse !== '') {
```suggestion
        if (!webauthnResponse) {
```

2022-07-08 13:27 UTC, undefined-moe commented on packages/hydrooj/src/handler/user.ts
> +            const result = webauthn.verifyAuthenticatorAssertionResponse(data, [udoc._authenticators]);
逻辑与API中重复

2022-07-08 13:27 UTC, undefined-moe commented on packages/hydrooj/src/model/user.ts
> +    _authenticators: string;
如果不支持同时添加多个密钥，请不要使用复数。

2022-07-08 13:27 UTC, undefined-moe commented on packages/ui-default/pages/home_security.page.ts
> +    user {
注意缩进。

2022-07-08 13:27 UTC, undefined-moe commented on packages/ui-default/pages/home_security.page.ts
> +    Notification.success(i18n('Successfully add.'));
注意词句语法。

2022-07-08 13:27 UTC, undefined-moe commented on packages/ui-default/pages/user_login.page.ts
> +          tfa,
多余的逗号

2022-07-08 13:27 UTC, undefined-moe commented on packages/ui-default/pages/user_login.page.ts
> +          user{
格式

2022-07-08 13:27 UTC, undefined-moe commented on packages/ui-default/templates/partials/login_dialog.html
> +        <div class="row pass_div"><div class="columns">
如果未添加 css，请不要使用 class 进行标记

2022-07-08 13:27 UTC, undefined-moe commented on packages/ui-default/pages/user_login.page.ts
> +    $('.use_password_btn').off('click').on('click', () => {
如果用户仅启用了硬件密钥，未启用 totp 两步验证，此处逻辑会出现问题。

2022-07-08 13:27 UTC, undefined-moe commented on packages/ui-default/pages/user_login.page.ts
> +    $('.webauthn_btn').off('click').on('click', async () => {
为何 `off('click')` ?

2022-07-08 13:27 UTC, undefined-moe commented on packages/ui-default/templates/home_security.html
> +            <p>{{ _('You Don\'t have a registered authenticator.') }}</p>
请在外层使用双引号。

2022-07-08 13:27 UTC, undefined-moe commented on packages/ui-default/templates/home_security.html
> +        {% if handler.user.tfa %}
同上，基于硬件密钥的验证应独立于基于时间的验证。

2022-07-08 13:27 UTC, undefined-moe requested changes
*

2022-07-08 15:46 UTC, pandadtdyy requested changes

2022-07-08 15:46 UTC, pandadtdyy commented on packages/ui-default/pages/user_login.page.ts
> +        $('.use_password_btn').show();
可以对这些按钮进行集中处理 包括但不限于包在div内 同时 由于并没有引入新的css 推荐使用#pass_div 和 #tfa_div 作为区分

2022-07-09 01:24 UTC, CodyNotFound commented on packages/ui-default/pages/user_login.page.ts
> +        $('.use_password_btn').show();
如果您本地跑一跑就会发现我为什么要这么做而不是使用id
虽然这么做不是个好的解决方案
已经找到了好的方法替代

2022-08-20 09:31 UTC, closed without merging