core&ui: add problems gql to fix autocomplete
hydro-dev/Hydro pull request #389
Opened 2022-07-17 09:30 UTC by pandadtdyy

2022-07-17 12:08 UTC, undefined-moe requested changes

2022-07-17 12:08 UTC, undefined-moe commented on packages/hydrooj/src/handler/problem.ts
> +        console.log(res);
?

2022-07-17 12:08 UTC, undefined-moe commented on packages/hydrooj/src/handler/problem.ts
> +        const res = await problem.getList(ctx.args.domainId, arg.ids);
use the arg indexByIdOnly

2022-07-17 12:13 UTC, pandadtdyy commented on packages/hydrooj/src/handler/problem.ts
> +        console.log(res);
原本写了prefix 后来发现prefix可以直接用search

2022-07-19 15:58 UTC, undefined-moe requested changes

2022-07-19 15:58 UTC, undefined-moe commented on packages/hydrooj/src/handler/problem.ts
> +    return Object.keys(res).map((id) => res[+id]);
is permission control required?
e.g. query hidden problem (in contest_edit) for admin user or problem creator

2022-07-21 12:59 UTC, undefined-moe approved these changes

2022-07-21 12:59 UTC, merged