vjudge: add support CSG-CPC online judge
hydro-dev/Hydro pull request #426
Opened 2022-09-06 14:55 UTC by guke1024

CSGOJ：https://cpc.csgrandeur.cn/

我好菜菜，undefined巨巨别骂骂

2022-09-06 14:59 UTC, pandadtdyy requested changes

2022-09-06 14:59 UTC, pandadtdyy commented on packages/vjudge/src/providers/csgoj.ts
> +export default class POJProvider implements IBasicProvider {
CSPOJProvider

2022-09-06 15:02 UTC, guke1024 commented on packages/vjudge/src/providers/csgoj.ts
> +export default class POJProvider implements IBasicProvider {
fixed

2022-09-06 15:07 UTC, undefined-moe requested changes

2022-09-06 15:07 UTC, undefined-moe commented on packages/vjudge/src/providers/csgoj.ts
> +            const status = VERDICT[res] || STATUS.STATUS_SYSTEM_ERROR;
如果 stat 是数字，为什么不直接映射到 `enum STATUS` 而要从 `VERDICT` 绕呢（

2022-09-06 15:07 UTC, undefined-moe commented on packages/vjudge/src/providers/csgoj.ts
> +            const memory = parseMemoryMB(`${result.body.rows[0].memory}K`) * 1024;
建议小写，下同

2022-09-06 15:07 UTC, undefined-moe commented on packages/vjudge/src/providers/csgoj.ts
> +            .set('User-Agent', 'Mozilla/5.0 (Windows NT 10.0; Win64; x64; rv:104.0) Gecko/20100101 Firefox/104.0')
`User-Agent` 可以提到 `this.get` 和 `this.post` 中统一设置，`X-Requested-With` 同

2022-09-06 15:07 UTC, undefined-moe commented on packages/vjudge/src/providers/csgoj.ts
> +            tag: [tag],
它只有一个tag吗

2022-09-06 15:07 UTC, undefined-moe commented on packages/vjudge/src/providers/csgoj.ts
> +            .set('Host', 'cpc.csgrandeur.cn');
Host 好像会自动设置。

2022-09-06 15:12 UTC, guke1024 commented on packages/vjudge/src/providers/csgoj.ts
> +            tag: [tag],
它本来的tag就是题面的source（

2022-09-06 15:13 UTC, guke1024 commented on packages/vjudge/src/providers/csgoj.ts
> +            const status = VERDICT[res] || STATUS.STATUS_SYSTEM_ERROR;
它的stat的数字对应的status和enum status不一样

2022-09-07 01:28 UTC, guke1024 commented on packages/vjudge/src/providers/csgoj.ts
> +            .set('User-Agent', 'Mozilla/5.0 (Windows NT 10.0; Win64; x64; rv:104.0) Gecko/20100101 Firefox/104.0')
`this.post` 已经统一设置，`this.get` 不行，有一处地方不能使用 `X-Requested-With`

2022-09-07 03:24 UTC, pandadtdyy requested changes

2022-09-07 03:24 UTC, pandadtdyy commented on packages/vjudge/src/providers/csgoj.ts
> +                .get(`/csgoj/Status/status_ajax?sort=solution_id_show&order=desc&offset=0&limit=20&problem_id=&user_id=&solution_id=${id}&language=-1&result=-1`)
只需要solution_id即可

2022-09-07 03:24 UTC, pandadtdyy commented on packages/vjudge/src/providers/csgoj.ts
> +            if (!src.startsWith('https')) src = `https://cpc.csgrandeur.cn${src}`;
new URL()

2022-09-07 03:24 UTC, pandadtdyy commented on packages/vjudge/src/providers/csgoj.ts
> +        const description = [...pDescription.children].map((i) => i.outerHTML).join('');
有一个东西叫BuildContent*

2022-09-07 03:24 UTC, pandadtdyy commented on packages/vjudge/src/providers/csgoj.ts
> +        const language = lang.includes('csgoj.') ? lang.split('csgoj.')[1] : '0';
他的lang是01234这种数字吗 如果是建议补在文件前面加个注释（不是强行 方便后人部署（？）） 然后限定域提交语言 不必问includes

2022-09-07 03:24 UTC, pandadtdyy commented on packages/vjudge/src/providers/csgoj.ts
> +                .get(`/csgoj/Status/status_ajax?sort=solution_id_show&order=desc&offset=0&limit=20&problem_id=&user_id=&solution_id=${id}&language=-1&result=-1`)
![image](https://user-images.githubusercontent.com/15662967/188781735-89c22305-89b8-4cb3-9c27-e76f448369d6.png)

2022-09-07 03:42 UTC, guke1024 commented on packages/vjudge/src/providers/csgoj.ts
> +        const description = [...pDescription.children].map((i) => i.outerHTML).join('');
其他都改了，就这个buildcontent是啥（）

2022-09-07 03:47 UTC, pandadtdyy commented on packages/vjudge/src/providers/csgoj.ts
> +        const description = [...pDescription.children].map((i) => i.outerHTML).join('');
import { buildContent } from 'hydrooj/src/lib/content';
用法参考migrate和cf

2022-09-07 03:51 UTC, guke1024 commented on packages/vjudge/src/providers/csgoj.ts
> +        const description = [...pDescription.children].map((i) => i.outerHTML).join('');
它里面有 `<span id="cb1-2">..|._|._||_||_.|_...||_||_|</span> 表格` 和 ` <em>d</em><sub>9</sub><em>d</em><sub>8</sub>⋯<em>d</em><sub>1</sub> 数学公式，这个恐怕不行

2022-09-08 09:26 UTC, undefined-moe approved these changes

2022-09-09 01:14 UTC, merged