contest: support 乐多赛制
hydro-dev/Hydro pull request #474
Opened 2022-12-21 02:39 UTC by smallfangqwq

支持了乐多赛制（ACM + IOI混合）并支持设置单次比率和最低比率。
将显示比赛类型的tag适配i18n

2022-12-21 02:56 UTC, smallfangqwq commented
I have read the CLA Document and I hereby sign the CLA

2022-12-21 03:01 UTC, undefined-moe commented
清注意：此 PR 似乎和 #472 存在冲突。建议修改 base branch 或是等待 #472 合并。

2022-12-21 11:37 UTC, pandadtdyy requested changes
You should rewrite some code because contest will have big changes, I wiil review this pr after #472 merge to master.

2022-12-21 11:37 UTC, pandadtdyy commented on packages/hydrooj/src/handler/contest.ts
> +        contestDuration: number = null, singleRatio :number, lowestRatio :number,
you need to run `yarn run lint`

2022-12-21 11:37 UTC, pandadtdyy commented on packages/hydrooj/src/handler/contest.ts
> +            if (rule === 'fun') {
Do not hardcode rule directly

2022-12-21 11:37 UTC, pandadtdyy commented on packages/hydrooj/src/interface.ts
> +    singleRatio: number;
They are unnecessary

2022-12-21 11:37 UTC, pandadtdyy commented on packages/ui-default/pages/contest_edit.page.ts
> +  $(document).on('change', '[name="rule"]', () => {
you needn't them after #472

2022-12-21 11:37 UTC, pandadtdyy commented on packages/ui-default/templates/contest_edit.html
> +          <div  id="fun-control">
wait #472

2022-12-21 12:11 UTC, smallfangqwq commented on packages/hydrooj/src/handler/contest.ts
> +            if (rule === 'fun') {
那就对于每一种规则新建一个参数"useContestRatioLimit"?

2022-12-21 12:14 UTC, pandadtdyy commented on packages/hydrooj/src/handler/contest.ts
> +            if (rule === 'fun') {
照常存入就好 其他的语言不会用到这几个参数 没有关系 你去看 #472 这里怎么写的就知道了

2022-12-24 13:21 UTC, undefined-moe requested changes

2022-12-24 13:21 UTC, undefined-moe commented on packages/hydrooj/src/model/contest.ts
> +    rated = false, data: Partial<Tdoc<30>> = {}, singleRatio = -1, lowestRatio = -1,
do not hardcode options related to specific contest rule into common arguments

2022-12-24 13:21 UTC, undefined-moe commented on packages/hydrooj/src/model/contest.ts
> +    if (singleRatio !== -1 && lowestRatio !== -1) {
did you notice the line just after your addition?

2022-12-24 13:21 UTC, undefined-moe commented on packages/ui-default/locales/zh.yaml
> +single_ratio: 每次错误提交倍率
Did you tell anyone, in any place, what these options are, and how they affect score calculation?

2023-01-05 15:18 UTC, pandadtdyy commented
I'm not sure you really know fun contest... The pr needs to be test.

2023-01-05 15:41 UTC, smallfangqwq commented
呃是有过测试的

2023-01-05 15:44 UTC, smallfangqwq commented
请您注意 如果这样修改会导致 在第二次错误没得满分时的得分是（分数）*0.95^1 而不是 0.95^2 请您再次确认 什么是提交次数 - 1
而这里为什么这么写的原因是，如果accept那么通过naccept计算的次数即为提交次数-1，反之是naccept即为当前次数。所以是需要当前是否ac的状态的。

另外一点是洛谷上经过确认提交成功后不会再降低倍率。

2023-01-05 15:58 UTC, pandadtdyy commented
那此处的表达应为 在本次提交前的错误提交次数 用naccept有一定的歧义

2023-01-05 16:02 UTC, smallfangqwq commented
naccept应该就是表示本题当前一共有多少次错误提交次数。这个表达的含义应该是没有歧义。

2023-01-05 16:03 UTC, smallfangqwq commented
所以才写了函数处理这一工作

2023-01-05 16:06 UTC, pandadtdyy commented
在此赛制中 你需要对外展示的naccept数 实际上也应该是 在本次提交前的错误提交次数 因此这样记录naccept也是有歧义的。

2023-01-05 16:07 UTC, smallfangqwq commented
是这样的。

2023-01-05 16:13 UTC, undefined-moe commented
~~似乎计分板中显示的应当是原分数而非乘算后分数，~~ 只有总分一列受影响。（可对总分使用两列，罚分后分数 / 原分数）
同时 分数乘算倍率可能挪进 hover 会更合适。

2023-01-05 16:14 UTC, undefined-moe commented
同时，根据描述，是否计入提交次数与提交是否通过无关。
若用户多次提交同一 AC 代码，其分数也应当受影响。

2023-01-05 16:15 UTC, smallfangqwq commented
> 同时，根据描述，是否计入提交次数与提交是否通过无关。 若用户多次提交同一 AC 代码，其分数也应当受影响。

在这点上我去洛谷进行了测试，其赛制在通过后再次提交不对成绩产生影响。

2023-01-05 16:24 UTC, pandadtdyy commented
PR将在询问洛谷具体赛制规则后由开发组直接重写。

2023-01-05 16:24 UTC, closed without merging