Update zh_TW.yaml
hydro-dev/Hydro pull request #485
Opened 2023-01-12 08:47 UTC by Alan2O18

update zh_TW.yaml translation

2023-01-12 08:48 UTC, Alan2O18 commented
I have read the CLA Document and I hereby sign the CLA

2023-01-12 12:34 UTC, undefined-moe requested changes
提交翻译前请先自行进行校对。

2023-01-12 15:33 UTC, pandadtdyy requested changes

2023-01-12 15:33 UTC, pandadtdyy commented on packages/ui-default/locales/zh_TW.yaml
> -'{0} comments': '{0} 條評論'
请不要直接对简体中文翻译至正體中文，在部分语句的翻译上两者存在偏差。

2023-01-12 15:33 UTC, pandadtdyy commented on packages/ui-default/locales/zh_TW.yaml
> -'Hello, {0}! You can click following link to reset the password of your {1} account:': 您好，{0}！您可以點選以下連結來重置您 {1} 賬戶的密碼：
不要对原有数据进行变动，除非翻译出错。

2023-01-12 16:36 UTC, undefined-moe commented
相关翻译工作应当交由 native speaker 进行。

2023-01-13 02:01 UTC, Alan2O18 commented on packages/ui-default/locales/zh_TW.yaml
> -'{0} comments': '{0} 條評論'
謝謝提醒
初次提交pr沒有做得很好的地方還請見諒
最新commit已經改用英文作為翻譯原文

2023-01-13 02:03 UTC, Alan2O18 commented on packages/ui-default/locales/zh_TW.yaml
> -'Hello, {0}! You can click following link to reset the password of your {1} account:': 您好，{0}！您可以點選以下連結來重置您 {1} 賬戶的密碼：
已經將沒有發生翻譯錯誤的原數據改回

2023-01-13 02:29 UTC, undefined-moe commented on packages/ui-default/locales/zh_TW.yaml
> -manage_edit: 編輯域資料
is this key missing?

2023-01-13 02:29 UTC, undefined-moe commented on packages/ui-default/locales/zh_TW.yaml
> -manage_permission: 管理許可權
ditto (you can use Github's pull request diff to check)

2023-01-13 02:29 UTC, undefined-moe commented on packages/ui-default/locales/zh_TW.yaml
> +The 'default' role applies to ALL REGISTERED USER.: default 角色作用於<b> 所有已註冊使用者</b>
you bolded a space

2023-01-13 03:09 UTC, Alan2O18 commented on packages/ui-default/locales/zh_TW.yaml
> -manage_edit: 編輯域資料
在最新版的簡體中文翻譯中
這些字詞似乎被刪掉了
這樣還要加回去嗎?

2023-01-13 03:11 UTC, undefined-moe commented on packages/ui-default/locales/zh_TW.yaml
> -manage_edit: 編輯域資料
这些关键字将在对应页面的标签页标题中出现。

2023-01-13 03:19 UTC, Alan2O18 commented on packages/ui-default/locales/zh_TW.yaml
> -manage_edit: 編輯域資料
所以在簡體翻譯中沒有出現的字詞可能不是被刪除
而只是被直接寫在其他地方?

2023-01-13 03:21 UTC, undefined-moe commented on packages/ui-default/locales/zh_TW.yaml
> -manage_edit: 編輯域資料
每个模块都可以提供部分相关的翻译文件，且可能存在部分 duplicate，将根据模块注册的优先级选择。

另请参照 `packages/hydrooj/locales/zh_TW.yaml`

2023-01-13 03:41 UTC, Alan2O18 commented on packages/ui-default/locales/zh_TW.yaml
> -manage_edit: 編輯域資料
已經將所有被刪除的字詞加回

2023-01-16 07:47 UTC, laosb commented
看起來翻譯品質不高，大片使用中國大陸用語而不是臺灣用語。

2023-01-20 04:24 UTC, Alan2O18 commented
> 看起來翻譯品質不高，大片使用中國大陸用語而不是臺灣用語，標點也沒使用臺灣現行規範。

已經針對使用中國用語的部分做出修正
如果依然有用語上的問題
歡迎直接標出
標點由中英直譯得出
可能與現行規範不合
若有更好的標點使用方法也歡迎指出

2023-01-20 06:05 UTC, undefined-moe commented
请注意：目前开发组成员均不熟悉 zh-Hant, 没有能力进行校对。同时，简繁互译并非仅字型区别，惯用词汇及表达方式也会有较大差异，因此我们才需要 native speaker 协助翻译。
同时，鉴于前期审理时出现的大量问题，我们对您是否真正熟悉繁体中文持怀疑态度。此 PR 可能会被搁置直到开发组内部有人能够进行校对为止。

2023-02-27 13:21 UTC, closed without merging