core: update zh.yaml
hydro-dev/Hydro pull request #64
Opened 2021-03-26 12:42 UTC by Macesuted

2021-03-26 14:25 UTC, undefined-moe requested changes

2021-03-26 14:25 UTC, undefined-moe commented on packages/hydrooj/locales/zh.yaml
> +'Copy "{data}" failed :(': '复制“{data}”失败 :('
为啥提前了

2021-03-26 14:25 UTC, undefined-moe commented on packages/hydrooj/locales/zh.yaml
> +'Effects only when Difficulty is not 'Use algorithm calculated'.': 仅当难度不为“使用算法计算”时才起效。
外层使用双引号

2021-03-26 14:25 UTC, undefined-moe commented on packages/hydrooj/locales/zh.yaml
> +Allow builtin-login: 使用默认登录方式
启用内置登录

2021-03-26 14:25 UTC, undefined-moe commented on packages/hydrooj/locales/zh.yaml
> +CDN Prefix: CDN 目录路径
CDN路径前缀

2021-03-26 14:25 UTC, undefined-moe commented on packages/hydrooj/locales/zh.yaml
> +Default display language: 网站默认语言
默认显示语言

2021-03-26 14:25 UTC, undefined-moe commented on packages/hydrooj/locales/zh.yaml
> +Disable builtin judge: 禁用内置评测机
这是judge模块的内容

2021-03-26 14:25 UTC, undefined-moe commented on packages/hydrooj/locales/zh.yaml
> +display name: 本域内显示名称
改来源吧 和底下统一

2021-03-26 14:25 UTC, undefined-moe commented on packages/hydrooj/locales/zh.yaml
> +Ensure index for problem search: 初始化 better-search 插件
同，这是search模块的

2021-03-26 14:25 UTC, undefined-moe commented on packages/hydrooj/locales/zh.yaml
> +From QDUOJ Export: 从 QDUOJ 导入
同

2021-03-26 14:25 UTC, undefined-moe commented on packages/hydrooj/locales/zh.yaml
> +Header Background: 顶部背景
这几个都是ui的

2021-03-26 14:25 UTC, undefined-moe commented on packages/hydrooj/locales/zh.yaml
> +IP Header: IP 头部
建议不翻译这个

2021-03-26 14:25 UTC, undefined-moe commented on packages/hydrooj/locales/zh.yaml
> +Max testcases per problem: 单题最多测试点数量
judge

2021-03-26 14:25 UTC, undefined-moe commented on packages/hydrooj/locales/zh.yaml
> +migrate from hustoj: 从 HustOJ 导入
hustoj

2021-03-26 14:25 UTC, undefined-moe commented on packages/hydrooj/locales/zh.yaml
> +migrate from vijos: 从 Vijos 导入
vijos

2021-03-26 14:25 UTC, undefined-moe commented on packages/hydrooj/locales/zh.yaml
> +Monaco language modes: 编译语言代号 -> Monaco 编辑器模式
ui

2021-03-26 14:25 UTC, undefined-moe commented on packages/hydrooj/locales/zh.yaml
> +Nav Logo Dark: 左上角小图标（暗）
都是ui

2021-03-26 14:25 UTC, undefined-moe commented on packages/hydrooj/locales/zh.yaml
> +pid: 题目编号
题目ID

2021-03-26 14:25 UTC, undefined-moe commented on packages/hydrooj/locales/zh.yaml
> +Retry delay sec: 错误时的重试等待秒数
judge

2021-03-26 14:25 UTC, undefined-moe commented on packages/hydrooj/locales/zh.yaml
> +Runner parallelism: 评测机运行进程数
judge

2021-03-26 14:25 UTC, undefined-moe commented on packages/hydrooj/locales/zh.yaml
> +Sandbox Host: 沙箱地址
judge

2021-03-26 14:25 UTC, undefined-moe commented on packages/hydrooj/locales/zh.yaml
> +Server BaseURL: 网站完整 URL
不建议翻译这些内容

2021-03-26 14:25 UTC, undefined-moe commented on packages/hydrooj/locales/zh.yaml
> +setting_storage: 存储设置
不翻译

2021-03-26 14:25 UTC, undefined-moe commented on packages/hydrooj/locales/zh.yaml
> +Stdout/Stderr size: 标准输出/错误流输出大小限制
judge

2021-03-26 14:25 UTC, undefined-moe commented on packages/hydrooj/locales/zh.yaml
> +Target: 目标域地址（格式形如：<域 ID>@<接收网站网址>，如 system@https://hydro.org.cn/）
存在对翻译表的污染，请考虑更改源内容

2021-03-26 14:25 UTC, undefined-moe commented on packages/hydrooj/locales/zh.yaml
> +Testdata cache directory: 测试数据缓存文件夹
judge

2021-03-26 14:25 UTC, undefined-moe commented on packages/hydrooj/locales/zh.yaml
> +Temp directory: 沙箱分区文件夹
judge

2021-03-26 14:25 UTC, undefined-moe commented on packages/hydrooj/locales/zh.yaml
> +Tmpfs size: 沙箱分区大小
judge

2021-03-26 14:25 UTC, undefined-moe commented on packages/hydrooj/locales/zh.yaml
> +Total time limit per problem: 单题最多总评测时长
judge

2021-03-27 00:45 UTC, undefined-moe requested changes

2021-03-27 00:45 UTC, undefined-moe commented on packages/hydrojudge/locales/zh.yaml
> +Retry delay sec: 错误时的重试等待秒数
重试间隔（秒）

2021-03-27 00:45 UTC, undefined-moe commented on packages/hydrojudge/locales/zh.yaml
> +Tmpfs size: 沙箱分区大小
tmpfs分区大小

2021-03-27 00:45 UTC, undefined-moe commented on packages/hydrojudge/locales/zh.yaml
> +Testdata cache directory: 测试数据缓存文件夹
测试数据缓存目录

2021-03-27 00:45 UTC, undefined-moe commented on packages/hydrojudge/locales/zh.yaml
> +Temp directory: 沙箱分区文件夹
临时目录

2021-03-27 00:45 UTC, undefined-moe commented on packages/hydrooj/locales/zh.yaml
> +Footer Extra HTML: 额外底部代码
无需翻译

2021-03-27 00:45 UTC, undefined-moe commented on packages/hydrooj/locales/zh.yaml
> +Language file settings: 评测机语言配置文件（langs.yaml）
评测机语言（langs.yaml）

2021-03-27 00:45 UTC, undefined-moe commented on packages/hydrooj/locales/zh.yaml
> +No testdata at current.: 暂无测试数据。╰(*°▽°*)╯
没测试数据怎么还这么开心啊草

2021-03-27 00:45 UTC, undefined-moe commented on packages/hydrooj/locales/zh.yaml
> +Target: 目标域地址
Target仅应该翻译为“目标”
同时比赛处有一处 Host -> 主持人 的翻译，存在污染，可考虑更换

2021-03-27 00:45 UTC, undefined-moe commented on packages/hydrooj/locales/zh.yaml
> +display name: 本域内显示名称
可删除

2021-03-27 00:45 UTC, undefined-moe commented on packages/hydrooj/src/model/setting.ts
> +    Setting('setting_info', 'displayName', null, 'text', 'Display name'),
Display Name

2021-03-27 00:47 UTC, undefined-moe commented
以及，考虑是否有必要对设置的文本进行翻译
这会影响用户使用关键字进行搜索。
尝试使用设置的Description字段存储此类数据？

2021-03-27 05:56 UTC, Macesuted commented
> 以及，考虑是否有必要对设置的文本进行翻译
> 这会影响用户使用关键字进行搜索。
> 尝试使用设置的Description字段存储此类数据？

已解决

2021-03-27 06:14 UTC, undefined-moe requested changes

2021-03-27 06:14 UTC, undefined-moe commented on packages/hydrooj/locales/zh.yaml
> +"What's file?": 什么是文件？
顺序错了

2021-03-27 06:17 UTC, undefined-moe approved these changes

2021-03-27 06:17 UTC, merged