vjudge: add hduoj
hydro-dev/Hydro pull request #654
Opened 2023-08-31 14:24 UTC by Lyricus233

demo: https://bpoj.top/d/hduoj/p

2023-09-20 18:51 UTC, undefined-moe commented
Please fix all CI issues before we can merge this pull request.

2023-09-22 14:13 UTC, pandadtdyy requested changes

2023-09-22 14:13 UTC, pandadtdyy commented on packages/vjudge/src/providers/hduoj.ts
> +        const res = await superagent.get(`http://acm.hdu.edu.cn/showproblem.php?pid=${id.split('P')[1]}`)
remove endPoint
```suggestion
        const res = await superagent.get(`/showproblem.php?pid=${id.split('P')[1]}`)
```

2023-09-23 11:09 UTC, LYkcul commented
hduoj language settings:

```
hduoj:
  display: HDUOJ
  execute: /bin/echo Invalid
  domain:
  - hduoj
hduoj.0:
  display: G++
  monaco: cpp
  highlight: cpp astyle-c
  comment: //
hduoj.1:
  display: GCC
  monaco: c
  highlight: c astyle-c
  comment: //
hduoj.2:
  display: C++
  monaco: cpp
  highlight: cpp astyle-c
  comment: //
hduoj.3:
  display: C
  monaco: c
  highlight: c astyle-c
  comment: //
hduoj.4:
  display: Pascal
  monaco: pascal
  highlight: pascal
  comment: //
hduoj.5:
  display: Java
  monaco: java
  highlight: java astyle-java
  comment: //
hduoj.6:
  display: C#
  monaco: plain
  highlight: plain
```

2023-10-10 21:50 UTC, undefined-moe requested changes

2023-10-10 21:50 UTC, undefined-moe commented on packages/vjudge/package.json
> +        "superagent-charset": "^1.2.0",
why devdeps?

2023-10-14 06:35 UTC, undefined-moe requested changes

2023-10-14 06:35 UTC, undefined-moe commented on packages/vjudge/package.json
> +        "@types/superagent": "^4.1.16",
why deps?

2023-10-20 13:32 UTC, undefined-moe approved these changes

2023-10-20 13:33 UTC, merged