vjudge: add yacs
hydro-dev/Hydro pull request #692
Opened 2023-11-30 14:21 UTC by Molmin

2023-11-30 22:57 UTC, undefined-moe requested changes

2023-11-30 22:57 UTC, undefined-moe commented on packages/vjudge/src/providers/yacs.ts
> +    评测机故障: STATUS.STATUS_SYSTEM_ERROR,
move these to ../verdict

2023-11-30 22:57 UTC, undefined-moe commented on packages/vjudge/src/providers/yacs.ts
> +        if (problem.background.trim()) content += `## 题目背景\n\n${problem.background.trim()}\n\n`;
i18n preferred

2023-11-30 22:57 UTC, undefined-moe commented on packages/vjudge/src/providers/yacs.ts
> +            'yacs.2': 'Python 3.6',
using a seperate scope is no longer recommended. please use `validAs` property.

https://github.com/hydro-dev/Hydro/blob/master/packages/vjudge/src/model.ts#L50

```
langs:
  cc:
    compile: g++ ...
    execute: /w/code
    validAs:
      yacs: C++
    ...
```

while the new format provides additional features like pretest.

2023-12-01 06:06 UTC, Molmin commented on packages/vjudge/src/providers/yacs.ts
> +        if (problem.background.trim()) content += `## 题目背景\n\n${problem.background.trim()}\n\n`;
> i18n preferred

这个网站全部是中文题目，感觉没必要用 i18n 吧？

另外怎么在后端用 i18n（）

2023-12-01 06:51 UTC, undefined-moe commented on packages/vjudge/src/verdict.ts
> +    // 答案错误: STATUS.STATUS_WRONG_ANSWER,
remove comments here

2023-12-01 08:47 UTC, undefined-moe approved these changes

2023-12-01 08:49 UTC, merged